// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace The_Food_Works_WebAPI.Models
{
    public partial class Batch
    {
        public Batch()
        {
            BatchLine = new HashSet<BatchLine>();
        }

        public int BatchId { get; set; }
        public int CookingListId { get; set; }
        public int BatchStatusId { get; set; }

        public virtual BatchStatus BatchStatus { get; set; }
        public virtual CookingList CookingList { get; set; }
        public virtual ICollection<BatchLine> BatchLine { get; set; }
    }
}