// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace The_Food_Works_WebAPI.Models
{
    public partial class CompletionMethod
    {
        public CompletionMethod()
        {
            Sale = new HashSet<Sale>();
        }

        public int CompletionMethodId { get; set; }
        public string CompletionMethodDescription { get; set; }

        public virtual ICollection<Sale> Sale { get; set; }
    }
}