// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace The_Food_Works_WebAPI.Models
{
    public partial class CookingList
    {
        public CookingList()
        {
            Batch = new HashSet<Batch>();
        }

        public int CookingListId { get; set; }
        public DateTime CookingListDate { get; set; }

        public virtual ICollection<Batch> Batch { get; set; }
    }
}