// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace The_Food_Works_WebAPI.Models
{
    public partial class ReportProductTrendsResult
    {
        public int quantity { get; set; }
        public string product_name { get; set; }
    }
}
