// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace The_Food_Works_WebAPI.Models
{
    public partial class ReportAccumulatedSalesResult
    {
        public double? SaleTotal { get; set; }
        public int? Year { get; set; }
        public int? Month { get; set; }
    }
}
