// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace The_Food_Works_WebAPI.Models
{
    public partial class RequestStatus
    {
        public RequestStatus()
        {
            BranchRequest = new HashSet<BranchRequest>();
        }

        public int RequestStatusId { get; set; }
        public string RequestStatusDescription { get; set; }

        public virtual ICollection<BranchRequest> BranchRequest { get; set; }
    }
}