// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace The_Food_Works_WebAPI.Models
{
    public partial class WriteOff
    {
        public WriteOff()
        {
            WriteOffProduct = new HashSet<WriteOffProduct>();
        }

        public int WriteOffId { get; set; }
        public DateTime WriteOffDate { get; set; }

        public virtual ICollection<WriteOffProduct> WriteOffProduct { get; set; }
    }
}