// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace The_Food_Works_WebAPI.Models
{
    public partial class BranchRequest
    {
        public BranchRequest()
        {
            BranchRequestLine = new HashSet<BranchRequestLine>();
        }

        public int BranchRequestId { get; set; }
        public DateTime? BranchRequestDate { get; set; }
        public int RequestStatusId { get; set; }
        public int BranchId { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual ICollection<BranchRequestLine> BranchRequestLine { get; set; }
    }
}