// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace The_Food_Works_WebAPI.Models
{
    public partial class ReportDailySalesResult
    {
        public string Month { get; set; }
        [Column("1")]
        public double _1 { get; set; }
        [Column("2")]
        public double _2 { get; set; }
        [Column("3")]
        public double _3 { get; set; }
        [Column("4")]
        public double _4 { get; set; }
        [Column("5")]
        public double _5 { get; set; }
        [Column("6")]
        public double _6 { get; set; }
        [Column("7")]
        public double _7 { get; set; }
        [Column("8")]
        public double _8 { get; set; }
        [Column("9")]
        public double _9 { get; set; }
        [Column("10")]
        public double _10 { get; set; }
        [Column("11")]
        public double _11 { get; set; }
        [Column("12")]
        public double _12 { get; set; }
        [Column("13")]
        public double _13 { get; set; }
        [Column("14")]
        public double _14 { get; set; }
        [Column("15")]
        public double _15 { get; set; }
        [Column("16")]
        public double _16 { get; set; }
        [Column("17")]
        public double _17 { get; set; }
        [Column("18")]
        public double _18 { get; set; }
        [Column("19")]
        public double _19 { get; set; }
        [Column("20")]
        public double _20 { get; set; }
        [Column("21")]
        public double _21 { get; set; }
        [Column("22")]
        public double _22 { get; set; }
        [Column("23")]
        public double _23 { get; set; }
        [Column("24")]
        public double _24 { get; set; }
        [Column("25")]
        public double _25 { get; set; }
        [Column("26")]
        public double _26 { get; set; }
        [Column("27")]
        public double _27 { get; set; }
        [Column("28")]
        public double _28 { get; set; }
        [Column("29")]
        public double _29 { get; set; }
        [Column("30")]
        public double _30 { get; set; }
        [Column("31")]
        public double _31 { get; set; }
    }
}
