// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace The_Food_Works_WebAPI.Models
{
    public partial class SupplierType
    {
        public SupplierType()
        {
            Supplier = new HashSet<Supplier>();
        }

        public int SupplierTypeId { get; set; }
        public string SupplierTypeName { get; set; }

        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}